apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: my-app-ingress
  namespace: staging
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
  - host: intodepth.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: myservice  # Replace with your actual service name
            port:
              number: 8080
